spring.application.name=TinyRoute
server.port=8080
jwt.secret=MINHA_CHAVE_SUPER_SECRETA_COM_MAIS_DE_32_CARACTERES
cors.allowed-origins=http://localhost:4200
app.base-url=http://tiny.route:8080/api/urls/r

spring.datasource.url=jdbc:postgresql://localhost:5432/Tinyroute_DB
spring.datasource.username=postgres
spring.datasource.password=123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.servlet.encoding.charset=UTF-8
spring.servlet.encoding.force=true